### ISSUE TITLE
add to janet-lang/pkgs

### ISSUE THREAD

**Issue by uvtc** [MikeBeller/janet-set#1]
Add janet-set to [the official Janet packages listing](https://github.com/janet-lang/pkgs/).

**Comment by MikeBeller** [comment]
Thanks @uvtc -- I understand that @pepe is now going to administer the official packages listing.  I had IMd him on Gitter and  he mentioned he was going to add in janet-set.  I wonder if I should still send a PR?

**Comment by pepe** [comment]
Oh, sorry, pretty please add the PR. That is the flow for now. I will not add packages at my discretion. 

My next task is to remove the confusion between @MikeBeller and me it seems.

**Comment by MikeBeller** [comment]
Haha!  Pull request added. :-)

**Comment by pepe** [comment]
And merged. Thank you for the patience :-)

**Comment by uvtc** [comment]
Cool! Yes, I figured that it's not really sustainable for Janet commandos to go around submitting PR's to pkgs they find in the wild. Better to just to create a ticket (GH issue) pointing out to the maintainer that it's not yet in janet-lang/pkgs. Then *they* can at their option check out the pkgs CONTRIBUTING doc, make any updates they may want to make, and submit the PR there themselves.

**Comment by uvtc** [comment]
Now if I could only figure out who's supposed to close a ticket/issue. The one who created it, or the maintainer? :)

**Comment by pepe** [comment]
First to come. 😀

That idea with PRing CONTRIBUTING doc is very good. I would link the second to last comment to the discussion.

**Comment by MikeBeller** [comment]
Ha.  Thanks I had made a note to myself to close once @pepe merged but you beat me to it @uvtc .  :-)
